In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

"""
STEP 0 >> imports; def clean
"""

# default cleaning method until proven otherwise
def clean_census_frame(csv_path , head=False , reset=True , set_index=False ):
    '''
    inputs) 
        >> csv_path
            > path to csv
        >> head
            > default=False
                >> if != False
                    > integer
                        >> returns the first {head} rows (using .head() method) 
                            > instead of enitre dataframe
        >> reset
            > default=True
                >> resets index after taking out rows
            > if set to False
                >> will not reset index
        >> set_index
            > default=False
            > if != False
                >> will set_index of new df to set_index
    output)
        >> dataframe cleaned like 2000 Census age&sex by 5-digit Zip Code (also how 2010 for same is cleaned)
    how)
        1. reads in csv , assumes it's large
        2. makes a copy for editing 
            > and potential future use
        3. locates readable column names  and non-readable names 
            > readable
                    > e.g. Estimate; SEX AND AGE - Total population
                >> assumes they are currently in row 0
            > non-readable
                    > e.g. HC01_VC03
                >> assumes they are currently == dataframe.columns
        4. replaces dataframe.columns (non-readable) with readable column names
            > and drops the old 0th column (column where readable names were stored)
        
    '''
    # load data
    df = pd.read_csv( csv_path , low_memory=False )

    # and copy
    _df = df.copy()

    # reset column names to current 0th row values
    _df.columns = _df.iloc[0]
    # new 2000 dataframe without row where values are from
    clean_df = _df[1:]
    
    # default
    if reset==True:
        # reset index
        clean_df = clean_df.reset_index()
        
    # set_index
    if set_index:
        clean_df = clean_df.set_index(set_index)
    
    if head:
        # return first {head} rows of dataframe
        return clean_df.head(head)
    else:
        # return dataframe
        return clean_df

'''
STEP 1 >> load data, reset; make copies
'''
def load_copy_data(i):
    '''
    loads data
    
    input)
        >> i
            > if 0
                >> .reset_index() after deleting row contining column names
            > if 1
                >> do not .reset_index()
                
    '''
    if i==0:
        # load with reset
        # 2011 
        twenty_eleven = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_11_5YR_DP05_with_ann.csv')
        # 2012
        twenty_twelve = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_12_5YR_DP05_with_ann.csv')
        #2013
        twenty_thirteen = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_13_5YR_DP05_with_ann.csv')
        # 2014
        twenty_fourteen = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_14_5YR_DP05_with_ann.csv')
        # 2015
        twenty_fifteen = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_15_5YR_DP05_with_ann.csv')
        #2016
        twenty_sixteen = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_16_5YR_DP05_with_ann.csv')
        #2017
        twenty_seventeen = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_17_5YR_DP05_with_ann.csv')
    if i==1:
        # load without reset
        # 2011 
        twenty_eleven = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_11_5YR_DP05_with_ann.csv',reset=False)
        # 2012
        twenty_twelve = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_12_5YR_DP05_with_ann.csv',reset=False)
        #2013
        twenty_thirteen = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_13_5YR_DP05_with_ann.csv',reset=False)
        # 2014
        twenty_fourteen = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_14_5YR_DP05_with_ann.csv',reset=False)
        # 2015
        twenty_fifteen = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_15_5YR_DP05_with_ann.csv',reset=False)
        #2016
        twenty_sixteen = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_16_5YR_DP05_with_ann.csv',reset=False)
        #2017
        twenty_seventeen = clean_census_frame('../../data/American_Community_Survey/aff_download/ACS_17_5YR_DP05_with_ann.csv',reset=False)
    
    # copy 
    # 2011 
    _y2k11 = twenty_eleven.copy()
    # 2012
    _y2k12 = twenty_twelve.copy()
    #2013
    _y2k13 = twenty_thirteen.copy()
    # 2014
    _y2k14 = twenty_fourteen.copy()
    # 2015
    _y2k15 = twenty_fifteen.copy()
    #2016
    _y2k16 = twenty_sixteen.copy()
    #2017
    _y2k17 = twenty_seventeen.copy()
    
    # output list of copied frames
    return [_y2k11,_y2k12,_y2k13,_y2k14,_y2k15,_y2k16,_y2k17]

In [2]:
# load w/o reset
f = load_copy_data(1)

In [3]:
# copy for safeguard and hedge reload
frames = f.copy()

In [4]:
# extract copy of 2011 
y2k11 = frames.copy()[0]

In [5]:
# examine (2011)
y2k11

0                  Id    Id2    Geography  \
1      8600000US00601  00601  ZCTA5 00601   
2      8600000US00602  00602  ZCTA5 00602   
3      8600000US00603  00603  ZCTA5 00603   
4      8600000US00606  00606  ZCTA5 00606   
5      8600000US00610  00610  ZCTA5 00610   
6      8600000US00612  00612  ZCTA5 00612   
7      8600000US00616  00616  ZCTA5 00616   
8      8600000US00617  00617  ZCTA5 00617   
9      8600000US00622  00622  ZCTA5 00622   
10     8600000US00623  00623  ZCTA5 00623   
11     8600000US00624  00624  ZCTA5 00624   
12     8600000US00627  00627  ZCTA5 00627   
13     8600000US00631  00631  ZCTA5 00631   
14     8600000US00637  00637  ZCTA5 00637   
15     8600000US00638  00638  ZCTA5 00638   
16     8600000US00641  00641  ZCTA5 00641   
17     8600000US00646  00646  ZCTA5 00646   
18     8600000US00647  00647  ZCTA5 00647   
19     8600000US00650  00650  ZCTA5 00650   
20     8600000US00652  00652  ZCTA5 00652   
21     8600000US00653  00653  ZCTA5 00653   
22     8600000US00656  00656  ZCTA5 00656   
23     8600000US00659  00659  ZCTA5 00659   
24     8600000US00660  00660  ZCTA5 00660   
25     8600000US00662  00662  ZCTA5 00662   
26     8600000US00664  00664  ZCTA5 00664   
27     8600000US00667  00667  ZCTA5 00667   
28     8600000US00669  00669  ZCTA5 00669   
29     8600000US00670  00670  ZCTA5 00670   
30     8600000US00674  00674  ZCTA5 00674   
...               ...    ...          ...   
33091  8600000US99786  99786  ZCTA5 99786   
33092  8600000US99788  99788  ZCTA5 99788   
33093  8600000US99789  99789  ZCTA5 99789   
33094  8600000US99790  99790  ZCTA5 99790   
33095  8600000US99791  99791  ZCTA5 99791   
33096  8600000US99801  99801  ZCTA5 99801   
33097  8600000US99820  99820  ZCTA5 99820   
33098  8600000US99824  99824  ZCTA5 99824   
33099  8600000US99825  99825  ZCTA5 99825   
33100  8600000US99826  99826  ZCTA5 99826   
33101  8600000US99827  99827  ZCTA5 99827   
33102  8600000US99829  99829  ZCTA5 99829   
33103  8600000US99830  99830  ZCTA5 99830   
33104  8600000US99832  99832  ZCTA5 99832   
33105  8600000US99833  99833  ZCTA5 99833   
33106  8600000US99835  99835  ZCTA5 99835   
33107  8600000US99836  99836  ZCTA5 99836   
33108  8600000US99840  99840  ZCTA5 99840   
33109  8600000US99841  99841  ZCTA5 99841   
33110  8600000US99901  99901  ZCTA5 99901   
33111  8600000US99903  99903  ZCTA5 99903   
33112  8600000US99918  99918  ZCTA5 99918   
33113  8600000US99919  99919  ZCTA5 99919   
33114  8600000US99921  99921  ZCTA5 99921   
33115  8600000US99922  99922  ZCTA5 99922   
33116  8600000US99923  99923  ZCTA5 99923   
33117  8600000US99925  99925  ZCTA5 99925   
33118  8600000US99926  99926  ZCTA5 99926   
33119  8600000US99927  99927  ZCTA5 99927   
33120  8600000US99929  99929  ZCTA5 99929   

0     Estimate; SEX AND AGE - Total population  \
1                                        18533   
2                                        41930   
3                                        54475   
4                                         6386   
5                                        29111   
6                                        70541   
7                                        10617   
8                                        24458   
9                                         5419   
10                                       45314   
11                                       26439   
12                                       35260   
13                                        1836   
14                                       25511   
15                                       19166   
16                                       30987   
17                                       37942   
18                                        5605   
19                                       15359   
20                                        3378   
21                                       14048   
22                                       21684   
23                                       41843   
24       

In [37]:
# copy df for editing
k11 = y2k11.copy()

'''split into 2 df and rejoin after convert to int'''
# df to save
save_k11 = k11.copy()
# columns to save
save_k11 = save_k11.copy()[save_k11.columns[:3]]

# df to edit
switch_k11 = k11.copy()
# columns to edit
switch_k11 = switch_k11.copy()[switch_k11.columns[3:]]

# edited columns
swapped_k11 = switch_k11.copy().apply(pd.to_numeric, errors='ignore')

# new (edited) dataframe
new_k11 = pd.concat([save_k11,swapped_k11],axis=1)

len(new_k11.columns)

407

In [29]:
# # pull column names
# k11_cols = y2k11.copy().columns[4:]
# for c in range(len(k11_cols)):
#     a = pd.Series(k11[k11_cols])
# #     k11.loc[[k11_cols][c]] = pd.to_numeric(a,errors='ignore')
# # pd.Series(k11[k11_cols[0]])

In [ ]:
k11_cols = y2k11.copy().columns
__k11_cols__ = y2k11.copy().columns[4:]
# len(k11_cols),len(__k11_cols__)
print(f'{__k11_cols__[:3]}\n{k11_cols[:3]}')

In [ ]:
for frame in frames:
    print(frame.info(),'\n')

In [ ]:
copies = frames[:2].copy()
for df in copies:
    for column in df.columns: 
        df[column] = pd.to_numeric([df[column]], errors='ignore')

- ***NOTE***:
    - path to mvp
        - whiteboard_pics/acs_5yr_11-17_path-to-mvp.jpg

In [ ]:
dataset_array = frames[0].values
dataset_array

In [ ]:
'''
STEP 2 >> find all columns which coexist across all dataframes at current position
'''
columns_by_frame = [frame.columns for frame in frames]
count_columns_by_frame = [len(frame) for frame in columns_by_frame]

In [ ]:
out = []
# for range of df with most columns
for count in range(len(max(count_columns_by_frame))):
    # if index of every frame is same as index of frame with most columns
    if [frame for frame in columns_by_frame][count] == frames[6][count]:
        out.append(count)
out

In [ ]:
# collect all
years = frames  # [y2k11,y2k12,y2k13,y2k14,y2k15,y2k16,y2k17]
for year in years:
    print(len(year.columns),'\n',year.info(),'\n\n')

In [ ]:
from sklearn.cluster import KMeans
import numpy as np

X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0]])

kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_

# array([1, 1, 1, 0, 0, 0], dtype=int32)
kmeans.predict([[0, 0], [12, 3]])
# array([1, 0], dtype=int32)
kmeans.cluster_centers_
# array([[10.,  2.], [ 1.,  2.]])

In [ ]:


# Scikit learn plays really well with Pandas, so I suggest you use it. Here's an example:

# In [1]: 
# import pandas as pd
# import numpy as np
# from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
data = np.reshape(np.random.randn(20),(10,2)) # 10 training examples
labels = np.random.randint(2, size=10) # 10 labels

# In [2]: 
X = pd.DataFrame(data)
y = pd.Series(labels)

# In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    random_state=0)

# In [4]: X_test
# Out[4]:

#      0       1
# 2   -1.39   -1.86
# 8    0.48   -0.81
# 4   -0.10   -1.83

# In [5]: y_test
# Out[5]:

# 2    1
# 8    1
# 4    1

In [ ]:
X_train

In [ ]:
# q=pd.read_csv('../../data/American_Community_Survey/aff_download/ACS_11_5YR_DP05_with_ann.csv')

In [ ]:
pizfsdazapizzaadsf = (2,1,0,4,32,7,2,9,5)
max(pizfsdazapizzaadsf)